// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybJvafgItd4r_LMKpvNa8MCQ-2VXj3bI',
    appId: '1:213355676528:web:3b94639c8c964aad1785b5',
    messagingSenderId: '213355676528',
    projectId: 'chat-de1f1',
    authDomain: 'chat-de1f1.firebaseapp.com',
    storageBucket: 'chat-de1f1.appspot.com',
    measurementId: 'G-NNDVRYBXSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46xbN_OeNV2BQW8KdIq29o0O8xQaQjCs',
    appId: '1:213355676528:android:955da62131651ea41785b5',
    messagingSenderId: '213355676528',
    projectId: 'chat-de1f1',
    storageBucket: 'chat-de1f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74-IGZK_WWtiYE_rZ9n9R44OhAudjPE8',
    appId: '1:213355676528:ios:2b5642f7be7fac291785b5',
    messagingSenderId: '213355676528',
    projectId: 'chat-de1f1',
    storageBucket: 'chat-de1f1.appspot.com',
    iosClientId: '213355676528-64p72jo1ted9qvbtl59p94m72m9kq2or.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74-IGZK_WWtiYE_rZ9n9R44OhAudjPE8',
    appId: '1:213355676528:ios:2b5642f7be7fac291785b5',
    messagingSenderId: '213355676528',
    projectId: 'chat-de1f1',
    storageBucket: 'chat-de1f1.appspot.com',
    iosClientId: '213355676528-64p72jo1ted9qvbtl59p94m72m9kq2or.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
